builds:
  - binary: janus
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64

archive:
  format_overrides:
    - goos: windows
      format: zip

release:
  github:
    owner: whilei
    repo: janus
  draft: true

brew:
  # Reporitory to push the tap to.
  github:
    owner: whilei
    name: janus

  # Folder inside the repository to put the formula.
  # Default is the root folder.
  folder: Formula

  # Your app's description
  # Default is empty
  description: "Shared CI deployer + version syntax tool for ETCDEV"
