platform: x64
clone_folder: c:\gopath\src\github.com\ethereumproject\janus-tests
os: Visual Studio 2015
environment:
  GOPATH: c:\gopath
  # You can set GCP_PASSWD here or in the AppVeyor Setting GUI.
  # If setting as below, the encrypted value should be different for each repo.
  GCP_PASSWD:
    secure: erzLJz7qT0kCJa+jZG6Sf9wwkfLYO2UDLzydkKTdwqA=
install:
  - set PATH=%GOPATH%\bin;c:\go\bin;C:\msys64\mingw64\bin;C:\msys64\usr\bin\;%PATH%

  # Install janus.
  - curl -sL https://raw.githubusercontent.com/ethereumproject/janus/master/get-windows.sh | bash
  - set PATH=./janusbin;%PATH%
  - echo %PATH%

  # Use janus to create version names.
  # Note that 'ps' tells AppVeyor to use PowerShell instead of default batch commands.
  - ps: $env:VERSION_BASE = "$(janus.exe version -format='%M.%m.x')"
  - ps: $env:VERSION = "$(janus.exe version)"
  - echo %VERSION_BASE% %VERSION%

  # Run tests and stuff.
  - echo %GOPATH%
  - go version
  - go env
  - go get golang.org/x/sys/windows

build_script:
  # Create binary for release.
  - go build -o brainy.exe main.go
  # Archive it.
  - 7z a brainy-win64-%VERSION%.zip brainy.exe

artifacts:
  - path: '*.zip'
    name: brainy

deploy_script:
  - ps: >-
      If ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
          janus.exe deploy -to="isaac-tests/squirrel/$env:VERSION_BASE/" -files='./*.zip' -key='./gcp-key.enc.json'
      }
